<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';


$configurator = new Nette\Configurator;

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(false);

$configurator->enableDebugger(__DIR__ . '/../log', 'adam.schubert@sg1-game.net');

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon');
$configurator->addParameters([
    'appDir' => __DIR__,
    'wwwDir' => dirname(__DIR__) . '/www',
]);
$container = $configurator->createContainer();

return $container;
